=== bastiancy/quena-mti/parte1/xml/store2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.example.org/store"
  xmlns:tns="http://www.example.org/store"
  elementFormDefault="qualified">

  <xs:element name="store">
    <xs:annotation>
      <xs:documentation>
        Quena store object schema
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        
        <xs:element name="direccion">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pais" />
              <xs:element name="region" />
              <xs:element name="ciudad" />
              <xs:element name="descripcion" />
              <xs:element name="zipcode" />
              <xs:element name="geo">
                  <xs:complexType>
                    <xs:attribute name="lat" type="xs:integer" />
                    <xs:attribute name="lon" type="xs:integer" />
                  </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="establecimiento">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" />
              <xs:element name="direccion" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="categoria">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" />
              <xs:element name="descripcion" />
              <xs:element name="categoriaPadre" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="producto">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="tipo" type="xs:string" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
              </xs:element>
              <xs:element name="nombre" />
              <xs:element name="marca" />
              <xs:element name="modelo" />
              <xs:element name="descripcion" />
              <xs:element name="origen" />
              <xs:element name="categorias">
                  <xs:complexType>
                    <xs:sequence>
                        <xs:element name="categoria" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="ref" type="xs:IDREF"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                  </xs:complexType>
              </xs:element>
              <xs:element name="caracteristicas">
                  <xs:complexType>
                    <xs:sequence>
                        <xs:element name="caracteristica" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                  <xs:extension base="xs:string">
                                    <xs:attribute name="nombre" type="xs:string" />
                                  </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                  </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="inventario">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="establecimiento" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="producto" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="codigo">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="tipo" type="xs:string" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
              </xs:element>
              <xs:element name="precio">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:decimal">
                        <xs:attribute name="moneda" type="xs:string" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
              </xs:element>
              <xs:element name="estado" />
              <xs:element name="fecha_actualizado" type="xs:date" />
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="cliente">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" />
              <xs:element name="apellido" />
              <xs:element name="email" />
              <xs:element name="fecha_registro" type="xs:date" />
              <xs:element name="estado" />
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="venta">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="establecimiento" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="cliente" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="pago">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:decimal">
                        <xs:attribute name="moneda" type="xs:string" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
              </xs:element>
              <xs:element name="estado" />
              <xs:element name="fecha_venta" type="xs:dateTime" />
            </xs:sequence>
            <xs:attribute name="class" type="xs:string" />
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>

        <xs:element name="itemVenta">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="venta" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="inventario" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="precio">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:decimal">
                        <xs:attribute name="moneda" type="xs:string" />
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== bastiancy/quena-mti/parte1/xml/store2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ex:store xmlns:ex="http://www.example.org/store"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.example.org/store store2.xsd ">

  <ex:direccion class="Direccion" id="id-101">
    <ex:pais>Chile</ex:pais>
    <ex:region>RM</ex:region>
    <ex:ciudad>Santiago</ex:ciudad>
    <ex:descripcion>Calle Falsa 123</ex:descripcion>
    <ex:zipcode>1111111</ex:zipcode>
    <ex:geo lat="123" lon="456" />
  </ex:direccion>

  <ex:establecimiento class="Establecimiento" id="id-201">
    <ex:nombre>Audiomusica</ex:nombre>
    <ex:direccion ref="id-101" />
  </ex:establecimiento>

  <ex:categoria class="Categoria" id="id-301">
    <ex:nombre>Cuerdas</ex:nombre>
    <ex:descripcion>Instrumentos de cuerdas con caja de resonancia</ex:descripcion>
    <ex:categoriaPadre ref="id-301" />
  </ex:categoria>

  <ex:producto class="Producto" id="id-401">
    <ex:codigo tipo="part_number">G123456</ex:codigo>
    <ex:nombre>Guitarra electrica</ex:nombre>
    <ex:marca>Ibanez</ex:marca>
    <ex:modelo>G1</ex:modelo>
    <ex:descripcion>Guitarra de 6 cuerdas estilo stratocaster</ex:descripcion>
    <ex:origen>Europa occidental</ex:origen>
    <ex:categorias>
        <ex:categoria ref="id-301" />
    </ex:categorias>
    <ex:caracteristicas>
        <ex:caracteristica nombre="color">negro</ex:caracteristica>
        <ex:caracteristica nombre="tipo cuerda">steel</ex:caracteristica>
        <ex:caracteristica nombre="numero cuerdas">6</ex:caracteristica>
    </ex:caracteristicas>
  </ex:producto>

  <ex:inventario class="Inventario" id="id-501">
    <ex:establecimiento ref="id-201" />
    <ex:producto ref="id-401" />
    <ex:codigo tipo="serial_number">123456789</ex:codigo>
    <ex:precio moneda="CLP">10000.0</ex:precio>
    <ex:estado>ingreso</ex:estado>
    <ex:fecha_actualizado>2017-01-01</ex:fecha_actualizado>
  </ex:inventario>

  <ex:cliente class="Cliente" id="id-601">
    <ex:nombre>Juan</ex:nombre>
    <ex:apellido>Gonzalez</ex:apellido>
    <ex:email>juan@example.com</ex:email>
    <ex:fecha_registro>2017-01-01</ex:fecha_registro>
    <ex:estado>activo</ex:estado>
  </ex:cliente>

  <ex:venta class="Venta" id="id-701">
    <ex:establecimiento ref="id-201" />
    <ex:cliente ref="id-601" />
    <ex:pago moneda="CLP">20000.0</ex:pago>
    <ex:estado>terminado</ex:estado>
    <ex:fecha_venta>2016-12-25T08:30:00</ex:fecha_venta>
  </ex:venta>

  <ex:itemVenta>
    <ex:venta ref="id-701" />
    <ex:inventario ref="id-501" />
    <ex:precio moneda="CLP">20000.0</ex:precio>
  </ex:itemVenta>

</ex:store>
